### ISSUE TITLE
When multiple mobs are attacking me, I can just walk away right when the first guy dies

### ISSUE THREAD

**Issue by kerowa** [prophecymud/prophecy-issues#17]
Not sure if this has always been the case?  Two murgo males were fighting me (the second aggroed) and when the first one died, I just walked to the next room.

**Comment by anhegofcherek** [comment]
Fixed in next reboot, thanks

(If you're interested: killing someone would unset your `fighting` pointer and set your position back to `POS_STANDING`, *then* in the periodic combat update handler, anyone not already in combat but with someone fighting them would be set to fight the person fighting them; if you got lucky you could use that timing gap to move. Rather than mess with the whole logic there, I've just tweaked the movement code to check if anyone's fighting you)

**Comment by kerowa** [comment]
Had totally forgotten about this -- thanks for fixing :)
